#!/bin/bash

SaveDir=`zenity --file-selection --directory --filename="$HOME/music/"`

if [ -n "$SaveDir" ]; then
    # name prompt
    # Name=`zenity --entry --text="Name"`
    cd $SaveDir
    # name prompt block
    if [ -n "$Name" ]; then
        # without progress
        youtube-dl -x -o "$Name.%(ext)s" --audio-format vorbis $1
        if [ $? -eq 0 ]; then
            notify-send "Download finished"
        else
            notify-send "Download failed!"
        fi

        # with progress
        # youtube-dl -x -o "$Name.%(ext)s" --audio-format vorbis $1 | \
        #     grep  --line-buffered -oP '\[download\].*?\K([0-9.]+\%)' | \
        #     zenity --progress --percentage=0
    else
        # without progress
        youtube-dl -x -o "%(title)s.%(ext)s" --audio-format vorbis $1
        if [ $? -eq 0 ]; then
            notify-send "Download finished"
        else
            notify-send "Download failed!"
        fi

        # with progress
        # youtube-dl -x -o "%(title)s.%(ext)s" --audio-format vorbis $1 | \
        #     grep  --line-buffered -oP '\[download\].*?\K([0-9.]+\%)' | \
        #     zenity --progress --percentage=0
    fi
fi
