#!/bin/bash

SaveDir=`zenity --file-selection --directory --filename="$HOME/music/"`

if [ -n "$SaveDir" ]; then
    Name=`zenity --entry --text="Name"`
    cd $SaveDir
    if [ -n "$Name" ]; then
        youtube-dl -x -o "$Name.%(ext)s" --audio-format vorbis $1 | \
            grep  --line-buffered -oP '\[download\].*?\K([0-9.]+\%)' | \
            zenity --progress --percentage=0
    else
        youtube-dl -x -o "%(title)s.%(ext)s" --audio-format vorbis $1 | \
            grep  --line-buffered -oP '\[download\].*?\K([0-9.]+\%)' | \
            zenity --progress --percentage=0
    fi
fi
